Repository langgenius/dify-official-plugins, pull requests merged in 2025-08, with the labels that each got.

#1533 feat: add qwen-mt models
  models/tongyi/manifest.yaml
  models/tongyi/models/llm/_position.yaml
  models/tongyi/models/llm/llm.py
  models/tongyi/models/llm/qwen-mt-plus.yaml
  models/tongyi/models/llm/qwen-mt-turbo.yaml
  models/tongyi/requirements.txt
Labels: enhancement, size:XL

#1539 fix(gemini-config): deprecate multiple gemini models and refine thinking/response modality config
  models/gemini/manifest.yaml
  models/gemini/models/llm/gemini-1.5-flash-001.yaml
  models/gemini/models/llm/gemini-1.5-flash-8b-exp-0827.yaml
  models/gemini/models/llm/gemini-1.5-flash-8b-exp-0924.yaml
  models/gemini/models/llm/gemini-1.5-flash-exp-0827.yaml
  models/gemini/models/llm/gemini-1.5-flash-latest.yaml
  models/gemini/models/llm/gemini-1.5-pro-001.yaml
  models/gemini/models/llm/gemini-1.5-pro-exp-0801.yaml
  models/gemini/models/llm/gemini-1.5-pro-exp-0827.yaml
  models/gemini/models/llm/gemini-2.0-pro-exp-02-05.yaml
  models/gemini/models/llm/gemini-2.0-pro-exp.yaml
  models/gemini/models/llm/gemini-2.5-flash-preview-04-17.yaml
  models/gemini/models/llm/gemini-2.5-pro-exp-03-25.yaml
  models/gemini/models/llm/gemini-exp-1114.yaml
  models/gemini/models/llm/gemini-exp-1121.yaml
  models/gemini/models/llm/gemini-exp-1206.yaml
  models/gemini/models/llm/learnlm-1.5-pro-experimental.yaml
  models/gemini/models/llm/llm.py
  models/gemini/provider/google.py
  models/gemini/pyproject.toml
Labels: enhancement, size:L, lgtm

#1537 feat: ComfyUI 0.2.3
  tools/comfyui/README.md
  tools/comfyui/manifest.yaml
  tools/comfyui/provider/comfyui.yaml
  tools/comfyui/tools/comfyui_client.py
  tools/comfyui/tools/comfyui_workflow.py
  tools/comfyui/tools/convert_to_api.py
  tools/comfyui/tools/convert_to_api.yaml
  tools/comfyui/tools/download_by_json.py
  tools/comfyui/tools/download_by_url.py
  tools/comfyui/tools/img2img.py
  tools/comfyui/tools/img2vid.py
  tools/comfyui/tools/json/comfyorg_templates/reference.txt
  tools/comfyui/tools/json/download.json
  tools/comfyui/tools/json/img2img.json
  tools/comfyui/tools/json/img2vid_wan2_2_14B.json
  tools/comfyui/tools/json/img2vid_wan2_2_5B.json
  tools/comfyui/tools/json/txt2img.json
  tools/comfyui/tools/json/txt2img_hiresfix.json
  tools/comfyui/tools/json/txt2vid_wan2_2_14B.json
  tools/comfyui/tools/json/txt2vid_wan2_2_5B.json
  tools/comfyui/tools/json/widgets_value_names.json
  tools/comfyui/tools/model_manager.py
  tools/comfyui/tools/run_workflow.py
  tools/comfyui/tools/run_workflow.yaml
  tools/comfyui/tools/txt2vid.py
  tools/comfyui/tools/txt2vid.yaml
Labels: enhancement, size:XXL, lgtm

#1540 Close resolved issues 0821
  models/gemini/README.md
Labels: documentation, size:XS, lgtm

#1546 feat(gemini): tool calling
  models/gemini/.claude/settings.local.json
  models/gemini/manifest.yaml
  models/gemini/models/llm/gemini-2.0-flash.yaml
  models/gemini/models/llm/gemini-2.5-flash-lite.yaml
  models/gemini/models/llm/gemini-2.5-flash.yaml
  models/gemini/models/llm/gemini-2.5-pro.yaml
  models/gemini/models/llm/llm.py
  models/gemini/models/llm/test_feature_compatibility.py
Labels: enhancement, size:XL

#1547 fix(tongyi): enable video processing for Qwen-VL-Plus model
  models/tongyi/manifest.yaml
  models/tongyi/models/llm/llm.py
Labels: bug, size:S, lgtm

#1551 feat: volcengine add deepseek-v3.1
  models/volcengine_maas/manifest.yaml
  models/volcengine_maas/models/llm/llm.py
  models/volcengine_maas/models/llm/models.py
  models/volcengine_maas/provider/volcengine_maas.yaml
Labels: enhancement, size:S

#1554 Gitee AI add support for new models
  models/gitee_ai/manifest.yaml
  models/gitee_ai/models/llm/Baichuan-M2-32B.yaml
  models/gitee_ai/models/llm/GLM-4_5-Air.yaml
  models/gitee_ai/models/llm/GLM-4_5.yaml
  models/gitee_ai/models/llm/GLM-4_5V.yaml
  models/gitee_ai/models/llm/Qwen3-235B-A22B-Instruct-2507.yaml
  models/gitee_ai/models/llm/Qwen3-30B-A3B-Instruct-2507.yaml
  models/gitee_ai/models/llm/Seed-X-PPO-7B.yaml
  models/gitee_ai/models/llm/_position.yaml
  models/gitee_ai/models/llm/gpt-oss-120b.yaml
  models/gitee_ai/models/llm/gpt-oss-20b.yaml
  models/gitee_ai/models/llm/kimi-k2-instruct.yaml
  models/gitee_ai/models/llm/qwen3-coder-480b-a35b-instruct.yaml
  models/gitee_ai/models/llm/step3.yaml
  models/gitee_ai/models/rerank/Qwen3-Reranker-0.6B.yaml
  models/gitee_ai/models/rerank/Qwen3-Reranker-4B.yaml
  models/gitee_ai/models/rerank/Qwen3-Reranker-8B.yaml
  models/gitee_ai/provider/gitee_ai.yaml
  untitled/pom.xml
Labels: enhancement, size:XXL

#1559 feat: dropbox, gitlab and tavily datasource
  datasources/dropbox_datasource/.difyignore
  datasources/dropbox_datasource/.env.example
  datasources/dropbox_datasource/.gitattributes
  datasources/dropbox_datasource/.gitignore
  datasources/dropbox_datasource/PRIVACY.md
  datasources/dropbox_datasource/README.md
  datasources/dropbox_datasource/_assets/icon.svg
  datasources/dropbox_datasource/datasources/dropbox.py
  datasources/dropbox_datasource/datasources/dropbox.yaml
  datasources/dropbox_datasource/main.py
  datasources/dropbox_datasource/manifest.yaml
  datasources/dropbox_datasource/provider/dropbox.py
  datasources/dropbox_datasource/provider/dropbox.yaml
  datasources/dropbox_datasource/requirements.txt
  datasources/gitlab_datasource/.difyignore
  datasources/gitlab_datasource/.env.example
  datasources/gitlab_datasource/.gitattributes
  datasources/gitlab_datasource/.gitignore
  datasources/gitlab_datasource/GUIDE.md
  datasources/gitlab_datasource/PRIVACY.md
  datasources/gitlab_datasource/README.md
  datasources/gitlab_datasource/_assets/icon.png
  datasources/gitlab_datasource/datasources/github.py
  datasources/gitlab_datasource/datasources/gitlab.py
  datasources/gitlab_datasource/datasources/gitlab.yaml
  datasources/gitlab_datasource/main.py
  datasources/gitlab_datasource/manifest.yaml
  datasources/gitlab_datasource/provider/gitlab.py
  datasources/gitlab_datasource/provider/gitlab.yaml
  datasources/gitlab_datasource/requirements.txt
  datasources/tavily_datasource/.difyignore
  datasources/tavily_datasource/.env.example
  datasources/tavily_datasource/.gitattributes
  datasources/tavily_datasource/.gitignore
  datasources/tavily_datasource/GUIDE.md
  datasources/tavily_datasource/PRIVACY.md
  datasources/tavily_datasource/README.md
  datasources/tavily_datasource/_assets/icon.svg
  datasources/tavily_datasource/datasources/search_extract.py
  datasources/tavily_datasource/datasources/search_extract.yaml
  datasources/tavily_datasource/main.py
  datasources/tavily_datasource/manifest.yaml
  datasources/tavily_datasource/provider/tavily_datasource.py
  datasources/tavily_datasource/provider/tavily_datasource.yaml
  datasources/tavily_datasource/requirements.txt
Labels: size:XXL

#1562 feat: dropbox
  datasources/dropbox_datasource/.difyignore
  datasources/dropbox_datasource/.env.example
  datasources/dropbox_datasource/.gitattributes
  datasources/dropbox_datasource/.gitignore
  datasources/dropbox_datasource/PRIVACY.md
  datasources/dropbox_datasource/README.md
  datasources/dropbox_datasource/_assets/icon.svg
  datasources/dropbox_datasource/datasources/dropbox.py
  datasources/dropbox_datasource/datasources/dropbox.yaml
  datasources/dropbox_datasource/main.py
  datasources/dropbox_datasource/manifest.yaml
  datasources/dropbox_datasource/provider/dropbox.py
  datasources/dropbox_datasource/provider/dropbox.yaml
  datasources/dropbox_datasource/requirements.txt
Labels: size:XXL

#1567 fix(gemini): filter unsupported file types before uploading to Gemini API
  models/gemini/.claude/settings.local.json
  models/gemini/manifest.yaml
  models/gemini/models/llm/llm.py
  models/gemini/models/llm/utils.py
  models/gemini/models/tests/TEST_INSTRUCTIONS.md
  models/gemini/models/tests/test_document_filtering.py
  models/gemini/models/tests/test_feature_compatibility.py
  models/gemini/models/tests/test_llm.py
  models/gemini/pyproject.toml
Labels: bug, size:XXL, lgtm

#1569 Fix structured output error using OpenAI api compatible #1568
  models/openai_api_compatible/manifest.yaml
  models/openai_api_compatible/models/llm/llm.py
Labels: bug, size:XS, lgtm

#1572 add: deepseek v3.1
  models/tongyi/manifest.yaml
  models/tongyi/models/llm/deepseek-v3.1.yaml
Labels: enhancement, size:M, lgtm

#1570 Fix #1551 volc model duplicate deepseek-v3.1 and missing kimi-k2
  models/volcengine_maas/manifest.yaml
  models/volcengine_maas/provider/volcengine_maas.yaml
Labels: bug, size:XS, lgtm

#1577 Fix/openrouter claude vision support issue #1576
  models/openrouter/manifest.yaml
  models/openrouter/models/llm/_position.yaml
  models/openrouter/models/llm/deepseek-chat-v3.1.yaml
  models/openrouter/models/llm/llm.py
Labels: bug, size:M, lgtm

#1586 feat: add response format support for structured output in volcengine models (doubao-seed-1.6)
  models/volcengine_maas/manifest.yaml
  models/volcengine_maas/models/client.py
  models/volcengine_maas/models/llm/llm.py
  models/volcengine_maas/models/llm/models.py
Labels: enhancement, size:M, lgtm

#1585 feat: add JSON and YAML extractors to dify_extractor
  tools/dify_extractor/manifest.yaml
  tools/dify_extractor/tools/dify_extractor.py
  tools/dify_extractor/tools/dify_extractor.yaml
  tools/dify_extractor/tools/json_extractor.py
  tools/dify_extractor/tools/yaml_extractor.py
Labels: enhancement, size:L, lgtm

#1593 feat: add qwen3 embedding and reranker models from siliconflow
  models/siliconflow/manifest.yaml
  models/siliconflow/models/rerank/qwen3-reranker-0.6b.yaml
  models/siliconflow/models/rerank/qwen3-reranker-4b.yaml
  models/siliconflow/models/rerank/qwen3-reranker-8b.yaml
  models/siliconflow/models/text_embedding/qwen3-embedding-0.6b.yaml
  models/siliconflow/models/text_embedding/qwen3-embedding-4b.yaml
  models/siliconflow/models/text_embedding/qwen3-embedding-8b.yaml
Labels: enhancement, size:M, lgtm

#1599 Added gmail plugins with multiple actions.
  tools/gmail/GUIDE.md
  tools/gmail/PRIVACY.md
  tools/gmail/README.md
  tools/gmail/_assets/icon.svg
  tools/gmail/main.py
  tools/gmail/manifest.yaml
  tools/gmail/provider/dify-gmail.py
  tools/gmail/provider/dify-gmail.yaml
  tools/gmail/requirements.txt
  tools/gmail/tools/add_attachment_to_draft.py
  tools/gmail/tools/add_attachment_to_draft.yaml
  tools/gmail/tools/draft_message.py
  tools/gmail/tools/draft_message.yaml
  tools/gmail/tools/flag_message.py
  tools/gmail/tools/flag_message.yaml
  tools/gmail/tools/get_message.py
  tools/gmail/tools/get_message.yaml
  tools/gmail/tools/list_drafts.py
  tools/gmail/tools/list_drafts.yaml
  tools/gmail/tools/search_messages.py
  tools/gmail/tools/search_messages.yaml
  tools/gmail/tools/send_draft.py
  tools/gmail/tools/send_draft.yaml
  tools/gmail/tools/send_message.py
  tools/gmail/tools/send_message.yaml
Labels: enhancement, size:XXL

#1605 fix(feat/datasource): bump sdk version to support new ref format for output schema
  tools/general_chunk/manifest.yaml
  tools/general_chunk/requirements.txt
  tools/parent_child_chunk/manifest.yaml
  tools/parent_child_chunk/requirements.txt
  tools/qa_chunk/manifest.yaml
  tools/qa_chunk/requirements.txt
Labels: bug, size:S

#1607 feat: box datasource
  datasources/box_datasource/.difyignore
  datasources/box_datasource/PRIVACY.md
  datasources/box_datasource/README.md
  datasources/box_datasource/_assets/box_app.png
  datasources/box_datasource/_assets/icon.svg
  datasources/box_datasource/datasources/box.py
  datasources/box_datasource/datasources/box.yaml
  datasources/box_datasource/main.py
  datasources/box_datasource/manifest.yaml
  datasources/box_datasource/provider/box.py
  datasources/box_datasource/provider/box.yaml
  datasources/box_datasource/requirements.txt
Labels: enhancement, size:XL

#1604 feat: ComfyUI 0.2.4
  tools/comfyui/README.md
  tools/comfyui/_assets/nodes.png
  tools/comfyui/manifest.yaml
  tools/comfyui/provider/comfyui.yaml
  tools/comfyui/tools/comfyui_client.py
  tools/comfyui/tools/comfyui_workflow.py
  tools/comfyui/tools/img2any.py
  tools/comfyui/tools/img2any.yaml
  tools/comfyui/tools/img2img.py
  tools/comfyui/tools/img2img.yaml
  tools/comfyui/tools/img2vid.py
  tools/comfyui/tools/json/flux_dev_fp8.json
  tools/comfyui/tools/json/flux_schnell_fp8.json
  tools/comfyui/tools/json/qwen_image.json
  tools/comfyui/tools/json/qwen_image_edit.json
  tools/comfyui/tools/json/widgets_value_names.json
  tools/comfyui/tools/model_manager.py
  tools/comfyui/tools/quickstart.py
  tools/comfyui/tools/quickstart.yaml
  tools/comfyui/tools/run_workflow.py
  tools/comfyui/tools/txt2img.py
  tools/comfyui/tools/txt2img.yaml
  tools/comfyui/tools/txt2vid.py
Labels: enhancement, size:XXL, lgtm
