Repository langgenius/dify-official-plugins, pull requests merged in 2025-09, with the labels that each got.

#1573 feat: add base url for gemini
  models/gemini/manifest.yaml
  models/gemini/models/llm/llm.py
  models/gemini/provider/google.yaml
Labels: enhancement, size:S, lgtm

#1616 fix(gitlab): bump sdk version
  tools/gitlab/manifest.yaml
  tools/gitlab/requirements.txt
Labels: size:XS

#1618 fix: ComfyUI 0.2.5
  tools/comfyui/main.py
  tools/comfyui/manifest.yaml
  tools/comfyui/provider/comfyui.py
  tools/comfyui/ruff.toml
  tools/comfyui/tools/comfyui_client.py
  tools/comfyui/tools/comfyui_workflow.py
  tools/comfyui/tools/convert_to_api.py
  tools/comfyui/tools/download_by_json.py
  tools/comfyui/tools/download_by_url.py
  tools/comfyui/tools/download_civitai.py
  tools/comfyui/tools/download_huggingface.py
  tools/comfyui/tools/image_info.py
  tools/comfyui/tools/img2any.py
  tools/comfyui/tools/img2img.py
  tools/comfyui/tools/img2vid.py
  tools/comfyui/tools/list_models.py
  tools/comfyui/tools/list_samplers.py
  tools/comfyui/tools/model_manager.py
  tools/comfyui/tools/quickstart.py
  tools/comfyui/tools/run_workflow.py
  tools/comfyui/tools/txt2img.py
  tools/comfyui/tools/txt2vid.py
Labels: size:XL, lgtm

#1622 fix: update minimum_dify_version for sharepoint datasource
  datasources/sharepoint_datasource/manifest.yaml
Labels: size:XS, lgtm

#1626 feat(openrouter): update GPT-5 models with new parameters and features
  models/openrouter/manifest.yaml
  models/openrouter/models/llm/gpt-5-chat.yaml
  models/openrouter/models/llm/gpt-5-mini.yaml
  models/openrouter/models/llm/gpt-5-nano.yaml
  models/openrouter/models/llm/gpt-5.yaml
Labels: enhancement, size:L, lgtm

#1625 feat(slack_bot): support markdown formatting
  extensions/slack_bot/README.md
  extensions/slack_bot/endpoints/slack.py
  extensions/slack_bot/manifest.yaml
  extensions/slack_bot/requirements.txt
Labels: enhancement, size:M, lgtm

#1613 feat: add jiandaoyun plugin
  tools/jiandaoyun/.difyignore
  tools/jiandaoyun/.env.example
  tools/jiandaoyun/PRIVACY.md
  tools/jiandaoyun/README.md
  tools/jiandaoyun/_assets/img.png
  tools/jiandaoyun/_assets/list_entry.png
  tools/jiandaoyun/_assets/logo.svg
  tools/jiandaoyun/_assets/reasoning_config.png
  tools/jiandaoyun/_assets/tools_usage.png
  tools/jiandaoyun/main.py
  tools/jiandaoyun/manifest.yaml
  tools/jiandaoyun/provider/jiandaoyun.py
  tools/jiandaoyun/provider/jiandaoyun.yaml
  tools/jiandaoyun/requirements.txt
  tools/jiandaoyun/tools/createRecord.py
  tools/jiandaoyun/tools/createRecord.yaml
  tools/jiandaoyun/tools/createRecords.py
  tools/jiandaoyun/tools/createRecords.yaml
  tools/jiandaoyun/tools/deleteRecord.py
  tools/jiandaoyun/tools/deleteRecord.yaml
  tools/jiandaoyun/tools/getApp.py
  tools/jiandaoyun/tools/getApp.yaml
  tools/jiandaoyun/tools/getEntry.py
  tools/jiandaoyun/tools/getEntry.yaml
  tools/jiandaoyun/tools/getRecord.py
  tools/jiandaoyun/tools/getRecord.yaml
  tools/jiandaoyun/tools/getRecords.py
  tools/jiandaoyun/tools/getRecords.yaml
  tools/jiandaoyun/tools/getWidgets.py
  tools/jiandaoyun/tools/getWidgets.yaml
  tools/jiandaoyun/tools/updateRecord.py
  tools/jiandaoyun/tools/updateRecord.yaml
  tools/jiandaoyun/utils/__init__.py
  tools/jiandaoyun/utils/httpclient.py
  tools/jiandaoyun/utils/json2table.py
Labels: enhancement, size:XXL, lgtm

#1641 Regolo models 01
  models/regolo/GUIDE.md
  models/regolo/README.md
  models/regolo/_assets/icon_l_en.svg
  models/regolo/_assets/icon_s_en.svg
  models/regolo/main.py
  models/regolo/manifest.yaml
  models/regolo/models/llm/Llama-3.1-8B-Instruct.yaml
  models/regolo/models/llm/Llama-3.3-70B-Instruct.yaml
  models/regolo/models/llm/Phi-4.yaml
  models/regolo/models/llm/Qwen2.5-VL-32B-Instruct.yaml
  models/regolo/models/llm/Qwen3-8B.yaml
  models/regolo/models/llm/_position.yaml
  models/regolo/models/llm/deepseek-r1-70b.yaml
  models/regolo/models/llm/gemma-3-27b-it.yaml
  models/regolo/models/llm/gpt-oss-120b.yaml
  models/regolo/models/llm/llama-guard3-8b.yaml
  models/regolo/models/llm/llm.py
  models/regolo/models/llm/maestrale-chat-v0.4-beta.yaml
  models/regolo/models/llm/mistral-small3.2.yaml
  models/regolo/models/llm/qwen3-coder-30b.yaml
  models/regolo/models/text_embedding/_position.yaml
  models/regolo/models/text_embedding/gte-Qwen2.yaml
  models/regolo/models/text_embedding/qwen3-embedding-8b.yaml
  models/regolo/models/text_embedding/text-embedding-3-small.yaml
  models/regolo/models/text_embedding/text_embedding.py
  models/regolo/provider/regolo.py
  models/regolo/provider/regolo.yaml
  models/regolo/requirements.txt
Labels: enhancement, size:XL, lgtm

#1647 Fix/datasource brightdata icon
  datasources/brightdata_datasource/_assets/icon.svg
  datasources/brightdata_datasource/manifest.yaml
Labels: size:XS, lgtm

#1643 fix: bedrock provider "Model name is required for non-converse API models" error
  models/bedrock/manifest.yaml
  models/bedrock/models/llm/llm.py
Labels: bug, size:XS, lgtm

#1652 alert subchunk_separator default to "\n"
  tools/parent_child_chunk/manifest.yaml
  tools/parent_child_chunk/tools/parent_child_chunk.yaml
Labels: lack of context, size:XS, lgtm

#1654 fix: Remove `rag` tag for Knowledge Pipeline related plugins, bump `minimum_dify_version`
  tools/dify_extractor/manifest.yaml
  tools/dify_extractor/provider/dify_extractor.yaml
  tools/general_chunk/manifest.yaml
  tools/general_chunk/provider/general_chunk.yaml
  tools/parent_child_chunk/manifest.yaml
  tools/parent_child_chunk/provider/parent_child_chunk.yaml
  tools/qa_chunk/manifest.yaml
  tools/qa_chunk/provider/qa_chunk.yaml
  tools/unstructured/manifest.yaml
  tools/unstructured/provider/unstructured.yaml
Labels: bug, size:M, lgtm

#1656 typo: 删除无用的 Maven 项目配置文件
  untitled/pom.xml
Labels: size:S, lgtm

#1665 feat: kimi k2
  models/moonshot/manifest.yaml
  models/moonshot/models/llm/kimi-k2-0905-preview.yaml
  models/moonshot/models/llm/kimi-k2-turbo-preview.yaml
Labels: enhancement, size:M, lgtm

#1668 Feat(aihubmix): support gemini 2.5 flash image
  models/aihubmix/main.py
  models/aihubmix/manifest.yaml
  models/aihubmix/models/llm/_position.yaml
  models/aihubmix/models/llm/anthropic.py
  models/aihubmix/models/llm/gemini-2.5-flash-image-preview.yaml
  models/aihubmix/models/llm/google.py
  models/aihubmix/models/llm/google2.py
  models/aihubmix/models/llm/utils.py
  models/aihubmix/requirements.txt
Labels: enhancement, size:XXL, lgtm

#1674 fix(datasource/aws_s3): remove print()
  datasources/aws_s3_storage/README.md
  datasources/aws_s3_storage/datasources/aws_s3_storage.py
  datasources/aws_s3_storage/manifest.yaml
Labels: bug, size:XS, lgtm

#1676 feat&fix: ComfyUI 0.2.6
  tools/comfyui/main.py
  tools/comfyui/manifest.yaml
  tools/comfyui/provider/comfyui.py
  tools/comfyui/tools/comfyui_client.py
  tools/comfyui/tools/comfyui_model_manager.py
  tools/comfyui/tools/comfyui_workflow.py
  tools/comfyui/tools/convert_to_api.py
  tools/comfyui/tools/download_by_json.py
  tools/comfyui/tools/download_by_url.py
  tools/comfyui/tools/download_civitai.py
  tools/comfyui/tools/download_huggingface.py
  tools/comfyui/tools/image_info.py
  tools/comfyui/tools/img2any.py
  tools/comfyui/tools/img2img.py
  tools/comfyui/tools/img2vid.py
  tools/comfyui/tools/list_models.py
  tools/comfyui/tools/list_samplers.py
  tools/comfyui/tools/quickstart.py
  tools/comfyui/tools/quickstart.yaml
  tools/comfyui/tools/run_workflow.py
  tools/comfyui/tools/txt2img.py
  tools/comfyui/tools/txt2vid.py
Labels: enhancement, size:L, lgtm

#1681 chore(tools/qa_chunk): remove useless dependencies
  tools/qa_chunk/manifest.yaml
  tools/qa_chunk/requirements.txt
Labels: size:XS, lgtm

#1682 chore(tools/general_chunk): remove useless dependencies
  tools/general_chunk/manifest.yaml
  tools/general_chunk/requirements.txt
Labels: size:XS, lgtm

#1685 feat(model): add longcat
  models/longcat/.env.example
  models/longcat/README.md
  models/longcat/_assets/icon_l_en.svg
  models/longcat/_assets/icon_s_en.svg
  models/longcat/main.py
  models/longcat/manifest.yaml
  models/longcat/models/llm/__init__.py
  models/longcat/models/llm/_position.yaml
  models/longcat/models/llm/llm.py
  models/longcat/models/llm/longcat-flash-chat.yaml
  models/longcat/provider/longcat.py
  models/longcat/provider/longcat.yaml
  models/longcat/requirements.txt
Labels: enhancement, size:L, lgtm

#1712 feat(xinference): add task parameter for jina-embeddings-v4 model
  models/xinference/manifest.yaml
  models/xinference/models/text_embedding/text_embedding.py
Labels: enhancement, size:XS

#1697 fix: update model versions and add new models for GPT-5 and Claude series
  models/cometapi/manifest.yaml
  models/cometapi/models/llm/_position.yaml
  models/cometapi/models/llm/anthropic/claude-opus-4-1-20250805.yaml
  models/cometapi/models/llm/openai/gpt-5-2025-08-07.yaml
  models/cometapi/models/llm/openai/gpt-5-chat-latest.yaml
  models/cometapi/models/llm/openai/gpt-5-mini-2025-08-07.yaml
  models/cometapi/models/llm/openai/gpt-5-mini.yaml
  models/cometapi/models/llm/openai/gpt-5-nano-2025-08-07.yaml
  models/cometapi/models/llm/openai/gpt-5-nano.yaml
  models/cometapi/models/llm/openai/gpt-5.yaml
  models/cometapi/tools/renew_model_list.py
  models/cometapi/tools/yaml_batch_operator.py
Labels: enhancement, size:XL, lgtm

#1719 chore: adjust tags and minimal_dify_version for knowledge pipeline plugins
  datasources/aws_s3_storage/manifest.yaml
  datasources/azure_blob/manifest.yaml
  datasources/box_datasource/manifest.yaml
  datasources/brightdata_datasource/manifest.yaml
  datasources/confluence_datasource/manifest.yaml
  datasources/dropbox_datasource/manifest.yaml
  datasources/firecrawl_datasource/manifest.yaml
  datasources/github/README.md
  datasources/github/manifest.yaml
  datasources/gitlab_datasource/manifest.yaml
  datasources/google_cloud_storage/manifest.yaml
  datasources/google_drive/manifest.yaml
  datasources/jina_datasource/manifest.yaml
  datasources/notion_datasource/manifest.yaml
  datasources/onedrive/README.md
  datasources/onedrive/manifest.yaml
  datasources/sharepoint_datasource/manifest.yaml
  datasources/tavily_datasource/manifest.yaml
  tools/dify_extractor/manifest.yaml
  tools/dify_extractor/provider/dify_extractor.yaml
  tools/general_chunk/manifest.yaml
  tools/general_chunk/provider/general_chunk.yaml
  tools/parent_child_chunk/manifest.yaml
  tools/parent_child_chunk/provider/parent_child_chunk.yaml
  tools/qa_chunk/manifest.yaml
  tools/qa_chunk/provider/qa_chunk.yaml
  tools/unstructured/manifest.yaml
Labels: size:L, lgtm

#1731 Add documentation to Lemonade Plugin
  models/lemonade/README.md
  models/lemonade/_assets/lemonade-01.png
  models/lemonade/_assets/lemonade-02.png
  models/lemonade/_assets/lemonade-03.png
  models/lemonade/_assets/lemonade-04.png
  models/lemonade/_assets/lemonade-banner.png
  models/lemonade/manifest.yaml
  models/lemonade/provider/lemonade.yaml
Labels: documentation, size:M, lgtm

#1733 update ModelScope model list
  models/modelscope/manifest.yaml
  models/modelscope/models/llm/_position.yaml
  models/modelscope/models/llm/c4ai-command-r-plus-08-2024.yaml
  models/modelscope/models/llm/deepseek-r1-0528.yaml
  models/modelscope/models/llm/deepseek-r1-distill-qwen-14b.yaml
  models/modelscope/models/llm/deepseek-r1-distill-qwen-32b.yaml
  models/modelscope/models/llm/deepseek-r1-distill-qwen-7b.yaml
  models/modelscope/models/llm/deepseek-v3.1.yaml
  models/modelscope/models/llm/deepseek-v3.yaml
  models/modelscope/models/llm/ernie-4.5-0.3b-pt.yaml
  models/modelscope/models/llm/ernie-4.5-21b-a3b-pt.yaml
  models/modelscope/models/llm/ernie-4.5-300b-a47b-pt.yaml
  models/modelscope/models/llm/ernie-4.5-vl-28b-a3b-pt.yaml
  models/modelscope/models/llm/glm-4.5.yaml
  models/modelscope/models/llm/kimi-k2-instruct.yaml
  models/modelscope/models/llm/llama-4-maverick-17b-128e-instruct.yaml
  models/modelscope/models/llm/llama-4-scout-17b-16e-instruct.yaml
  models/modelscope/models/llm/minimax-m1-80k.yaml
  models/modelscope/models/llm/qwen2.5-vl-32B-instruct.yaml
  models/modelscope/models/llm/qwen2.5-vl-3B-instruct.yaml
  models/modelscope/models/llm/qwen2.5-vl-72B-instruct.yaml
  models/modelscope/models/llm/qwen2.5-vl-7B-instruct.yaml
  models/modelscope/models/llm/qwen3-0.6B.yaml
  models/modelscope/models/llm/qwen3-1.7B.yaml
  models/modelscope/models/llm/qwen3-14B.yaml
  models/modelscope/models/llm/qwen3-235B-A22B.yaml
  models/modelscope/models/llm/qwen3-235b-a22b-instruct-2507.yaml
  models/modelscope/models/llm/qwen3-235b-a22b-thinking-2507.yaml
  models/modelscope/models/llm/qwen3-30B-A3B.yaml
  models/modelscope/models/llm/qwen3-30b-a3b-thinking-2507.yaml
  models/modelscope/models/llm/qwen3-32B.yaml
  models/modelscope/models/llm/qwen3-4B.yaml
  models/modelscope/models/llm/qwen3-8B.yaml
  models/modelscope/models/llm/qwen3-coder-30b-a3b-instruct.yaml
  models/modelscope/models/llm/qwen3-coder-480b-a35b-instruct.yaml
  models/modelscope/models/llm/qwen3-next-80b-a3b-instruct.yaml
  models/modelscope/models/llm/qwen3-next-80b-a3b-thinking.yaml
  models/modelscope/models/llm/step3.yaml
Labels: enhancement, size:XXL, lgtm

#1735 fix: gpt-5 token
  models/openai/manifest.yaml
  models/openai/models/llm/llm.py
Labels: bug, size:XS, lgtm

#1740 Gemini image 0.1.0
  tools/gemini_image/README.md
  tools/gemini_image/main.py
  tools/gemini_image/manifest.yaml
  tools/gemini_image/provider/gemini_image.py
  tools/gemini_image/provider/gemini_image.yaml
  tools/gemini_image/requirements.txt
  tools/gemini_image/ruff.toml
  tools/gemini_image/tools/image_generate.py
  tools/gemini_image/tools/image_generate.yaml
Labels: documentation, size:L, lgtm

#1743 feat&fix: ComfyUI 0.3.1
  tools/comfyui/manifest.yaml
  tools/comfyui/provider/comfyui.yaml
  tools/comfyui/requirements.txt
  tools/comfyui/tools/comfyui_client.py
  tools/comfyui/tools/comfyui_model_manager.py
  tools/comfyui/tools/download_by_url.py
  tools/comfyui/tools/download_civitai.py
  tools/comfyui/tools/download_huggingface.py
  tools/comfyui/tools/img2any.py
  tools/comfyui/tools/img2img.py
  tools/comfyui/tools/img2img.yaml
  tools/comfyui/tools/img2vid.py
  tools/comfyui/tools/quickstart.py
  tools/comfyui/tools/run_workflow.py
  tools/comfyui/tools/txt2aud.py
  tools/comfyui/tools/txt2img.py
  tools/comfyui/tools/txt2img.yaml
  tools/comfyui/tools/txt2vid.py
Labels: size:L, lgtm

#1727 Feat/dingo rule list
  .github/workflows/pre-check-plugin.yaml
  tools/dingo/manifest.yaml
  tools/dingo/tools/text_quality_evaluator.py
  tools/dingo/tools/text_quality_evaluator.yaml
Labels: enhancement, size:L, lgtm

#1748 fix: add missing dify_plugin dependency to requirements.txt
  tools/dingo/manifest.yaml
  tools/dingo/requirements.txt
Labels: bug, size:XS, lgtm

#1754 feat(openrouter): add Grok 4 Fast Free model and update gpt-5-chat configuration
  models/openrouter/manifest.yaml
  models/openrouter/models/llm/_position.yaml
  models/openrouter/models/llm/gpt-5-chat.yaml
  models/openrouter/models/llm/grok-4-fast-free.yaml
  models/openrouter/models/llm/llm.py
Labels: enhancement, size:L, lgtm

#1760 feat: add qwen3-max
  models/tongyi/manifest.yaml
  models/tongyi/models/llm/_position.yaml
  models/tongyi/models/llm/qwen3-max-2025-09-23.yaml
  models/tongyi/models/llm/qwen3-max.yaml
Labels: enhancement, size:L, lgtm

#1773 feat(gemini): add `gemini-flash-latest` and `gemini-flash-lite-latest` models
  models/gemini/manifest.yaml
  models/gemini/models/llm/_position.yaml
  models/gemini/models/llm/gemini-2.5-flash-image-preview.yaml
  models/gemini/models/llm/gemini-flash-latest.yaml
  models/gemini/models/llm/gemini-flash-lite-latest.yaml
Labels: enhancement, size:L, lgtm

#1772 feat: ComfyUI 0.3.2
  tools/comfyui/README.md
  tools/comfyui/manifest.yaml
  tools/comfyui/tools/json/qwen_image_edit_2509_1img.json
  tools/comfyui/tools/json/qwen_image_edit_2509_2imgs.json
  tools/comfyui/tools/json/qwen_image_edit_2509_3imgs.json
  tools/comfyui/tools/json/widgets_value_names.json
  tools/comfyui/tools/quickstart.py
  tools/comfyui/tools/quickstart.yaml
Labels: enhancement, size:XL, lgtm

#1774 feat(mineru): add backend options for mineru2.5
  tools/mineru/manifest.yaml
  tools/mineru/tools/parse.py
  tools/mineru/tools/parse.yaml
Labels: enhancement, size:M, lgtm

#1765 chore: update plugin versions and refine error handling across multip…
  datasources/azure_blob/manifest.yaml
  datasources/azure_blob/requirements.txt
  datasources/confluence_datasource/datasources/confluence_datasource.py
  datasources/confluence_datasource/manifest.yaml
  datasources/confluence_datasource/provider/confluence_datasource.py
  datasources/dropbox_datasource/manifest.yaml
  datasources/dropbox_datasource/requirements.txt
  datasources/firecrawl_datasource/datasources/crawl.py
  datasources/firecrawl_datasource/manifest.yaml
  datasources/github/manifest.yaml
  datasources/github/requirements.txt
  datasources/gitlab_datasource/manifest.yaml
  datasources/gitlab_datasource/requirements.txt
  datasources/notion_datasource/datasources/notion_datasource.py
  datasources/notion_datasource/manifest.yaml
  datasources/onedrive/manifest.yaml
  datasources/onedrive/requirements.txt
  datasources/tavily_datasource/datasources/search_extract.py
  datasources/tavily_datasource/manifest.yaml
  datasources/tavily_datasource/requirements.txt
Labels: size:M, lgtm

#1776 Feature/resume optimizer
  tools/dingo/manifest.yaml
  tools/dingo/provider/dingo.yaml
  tools/dingo/tools/resume_optimizer.py
  tools/dingo/tools/resume_optimizer.yaml
Labels: enhancement, size:L, lgtm

#1775 fix(modelscope): 修复视觉模型支持问题
  models/modelscope/manifest.yaml
  models/modelscope/models/llm/_position.yaml
  models/modelscope/models/llm/ernie-4.5-vl-28b-a3b-pt.yaml
  models/modelscope/models/llm/llm.py
  models/modelscope/models/llm/qwen2.5-vl-32B-instruct.yaml
  models/modelscope/models/llm/qwen2.5-vl-3B-instruct.yaml
  models/modelscope/models/llm/qwen2.5-vl-72B-instruct.yaml
  models/modelscope/models/llm/qwen2.5-vl-7B-instruct.yaml
  models/modelscope/models/llm/qwen3-vl-235b-a22b-instruct.yaml
Labels: size:L, lgtm

#1785 feat: siliconflow add DeepSeek-V3.1-Terminus
  models/siliconflow/manifest.yaml
  models/siliconflow/models/llm/deepseek-v3.1-terminus-pro.yaml
  models/siliconflow/models/llm/deepseek-v3.1-terminus.yaml
Labels: enhancement, size:L, lgtm
